spring.datasource.url=jdbc:mysql://45.63.64.138:3306/QL_WebBanQuanAoCaNhan?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=thuan
spring.datasource.password=Thuan@123456